Refactor viewLog.ts to use @guardian/libs storage
guardian/dotcom-rendering pull request #10083
Opened 2024-01-08 13:20 UTC by DanielCliftonGuardian

## What does this change?
Refactor viewLog.ts to use @guardian/libs storage as part of https://github.com/guardian/dotcom-rendering/issues/10052
## Why?
Closes https://github.com/guardian/dotcom-rendering/issues/10081
## Screenshots
N/A

2024-01-08 13:48 UTC, mxdvl requested changes

2024-01-08 13:48 UTC, mxdvl commented on dotcom-rendering/src/components/marketing/lib/viewLog.ts
> +	const viewLog = (Array.isArray(item) ? item : []) as EpicView[];
I think we should reuse `getEpicViewLog` here instead

2024-01-08 13:48 UTC, mxdvl commented on dotcom-rendering/src/components/marketing/lib/viewLog.ts
>  		value: viewLog.slice(-maxLogEntries),
We need to update `newValue` so it’s the actually an array, not an object containing the `value` key containing the array.

```ts
const newValue = viewLog.slice(-maxLogEntries);
storage.local.set(viewLogKey, newValue);
```

2024-01-09 09:33 UTC, tjmw approved these changes
LGTM!

2024-01-09 11:57 UTC, mxdvl approved these changes

2024-01-10 11:56 UTC, merged