Limit banner height and allow scroll
guardian/dotcom-rendering pull request #1988
Opened 2020-10-19 15:16 UTC by tomrf1

We have had reports of the close button being out of view on our banners if the user has set a very high font size in their browser.
This is because the banner container is `position: fixed`.

We can ensure the button is not too high with `80vh`.
This doesn't work for the width, which still overflows. So we allow scrolling in this case. This problem is specific to mobile.

TODO - screenshots

2020-10-20 07:54 UTC, TomPretty approved these changes
👍

2020-10-20 08:39 UTC, liywjl reviewed
This feels like a work around for a more fundamental issue of how we should display text at that screen width. Idk if it maybe worth bringing this up with @HarryFischer ? @gtrufitt do you think this is an ok workaround in the meantime?

Side note: the background article seems to have lots of format issues, is that something that should be raised?

2020-10-20 09:05 UTC, tomrf1 commented
Yes if we just used px instead of rem then it wouldn't be an issue, but would that make it less accessible?

2020-10-20 09:29 UTC, liywjl commented
@tomrf1 could you add a couple more details to replicate this locally? 

I spoke to @HarryFischer who suggests it may be best to avoid having a left right scroll for the text as button, and instead make sure that the user can only scroll up and down.

This may require the banner to be reworked at certain breakpoints

2020-10-20 09:30 UTC, liywjl requested changes
@tomrf1 could you add a couple more details to replicate this locally?

I spoke to @HarryFischer who suggests it may be best to avoid having a left right scroll for the text as button, and instead make sure that the user can only scroll up and down.

This may require the banner to be reworked at certain breakpoints

2020-10-22 06:53 UTC, tomrf1 commented
@liywjl to reproduce this, set the browser's font size to e.g. 40. To get the banner to display again you can use a private browser window.
Because we define our font sizes in rem, it overflows. So I don't think this is a case of needing to change the banner layout at different breakpoints. We either set font size in px (making it less accessible?), or allow scrolling.

2020-10-26 15:04 UTC, liywjl approved these changes
Good workaround for the current issue.

Will need a better solution requiring some redesigns for the banner on these widths. Notable things to consider:

- needing to scroll left and right on mobile is uncomfortable (always favor up-down scroll)
- we should be able to see the close button on load (ideally no need to scroll to see it)
- text could be smaller, but should no break accessibility principles

2020-10-26 15:05 UTC, tomrf1 commented
Thanks @liywjl !
As a quick fix we will go ahead with this PR, and the contributions team will look into improving the design of the banner on mobile

2020-10-27 07:56 UTC, merged