Atom rendering Youtube
guardian/dotcom-rendering pull request #2199
Opened 2020-12-04 13:53 UTC by liywjl

## What does this change?
Update atoms-rendering to enable youtube analytics.

## Why?
Need to add analytics to youtube

2020-12-04 13:59 UTC, oliverlloyd requested changes
Can we add some tests for this atom? We've got the `atom.interactivity.spec.js` where we already check other atoms and because we removed the tests on atoms-rendering we currently have reduce coverage. I know there's pressure to get this one out but I think now is the right time to reintroduce this coverage in DCR to make sure that this functionality doesn't break in production without us knowing about it

2020-12-04 14:05 UTC, liywjl commented
superseded by https://github.com/guardian/dotcom-rendering/pull/2199

2020-12-04 19:20 UTC, oliverlloyd commented on package.json
> +        "youtube-player": "^5.5.2"
Shouldn't this be a dependency of the atoms-rendering package?

2021-01-25 11:47 UTC, liywjl commented
superceded by https://github.com/guardian/dotcom-rendering/pull/2285

2021-01-25 11:47 UTC, closed without merging