Labs Colouring
guardian/dotcom-rendering pull request #2709
Opened 2021-03-16 17:50 UTC by oliverlloyd

## What does this change?
Adds colours for `Special.Labs` articles

### Before
<img width="1411" alt="Screenshot 2021-03-16 at 17 50 20" src="https://user-images.githubusercontent.com/1336821/111356259-19b28d80-8680-11eb-98d3-f5f318f929a0.png">

### After
<img width="1411" alt="Screenshot 2021-03-16 at 17 49 22" src="https://user-images.githubusercontent.com/1336821/111356136-f851a180-867f-11eb-9216-d65a7bf94668.png">

## Why?
More greys and blacks

2021-03-16 17:51 UTC, oliverlloyd commented
@ioanna0 @HarryFischer @mxdvl thanks for helping on this!

2021-03-16 17:55 UTC, oliverlloyd commented
![](https://github.trello.services/images/mini-trello-icon.png) [Labs colouring (via palette)](https://trello.com/c/OAwbb8Dd/2660-labs-colouring-via-palette)

2021-03-16 18:12 UTC, HarryFischer commented on src/web/lib/decidePalette.ts
> +const BLACK = neutral[0];
```suggestion
const BLACK = neutral[7];
```
My bad here - neutral.0 is #000. We wanted neutral.7 #121212

2021-03-16 18:13 UTC, HarryFischer commented on src/web/lib/decidePalette.ts
> +	if (format.theme === Special.Labs) return neutral[86];
```suggestion
	if (format.theme === Special.Labs) return neutral[97];
```
Doms new designs use this bg colour instead for higher contrast

2021-03-16 18:14 UTC, HarryFischer requested changes
Couple colour tweaks to match new (accessible) designs

2021-03-17 09:54 UTC, HarryFischer approved these changes
👍

2021-03-17 10:24 UTC, liywjl approved these changes
LGTM 👍

2021-03-17 10:27 UTC, merged